/**
 * export-sql.js — Convert data.json into a single .sql file you can paste
 * into the Supabase SQL editor.  Use when you don't want to share the
 * service role key with the seed script.
 *
 * Run with:  node scripts/seed-catalog/export-sql.js
 * Then:      copy data.sql contents → Supabase SQL editor → Run
 */

import fs   from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const IN  = path.join(__dirname, "data.json");
const OUT = path.join(__dirname, "data.sql");

const sqlString = (s) => "'" + String(s ?? "").replace(/'/g, "''") + "'";
const sqlNullable = (s) => (s == null ? "NULL" : sqlString(s));
const sqlArray = (arr) => "ARRAY[" + (arr || []).map(sqlString).join(",") + "]::text[]";
const sqlJson  = (o)   => sqlString(JSON.stringify(o ?? {}));

async function main() {
  const rows = JSON.parse(await fs.readFile(IN, "utf8"));
  const lines = [
    "-- Auto-generated by export-sql.js — do not edit by hand.",
    "-- Inserts ~" + rows.length + " curated catalog rows.",
    "BEGIN;",
    "",
  ];

  for (const r of rows) {
    lines.push(
      `INSERT INTO items (category_id, title, creators, cover_url, description, ` +
      `published_at, published_year, published_month, genres, tags, external_ids, metadata, is_verified, source, source_id) VALUES (`,
      `  ${sqlString(r.category_id)},`,
      `  ${sqlString(r.title)},`,
      `  ${sqlArray(r.creators)},`,
      `  ${sqlNullable(r.cover_url)},`,
      `  ${sqlNullable(r.description)},`,
      `  ${r.published_at ? sqlString(r.published_at) + "::date" : "NULL"},`,
      `  ${r.published_year ?? "NULL"},`,
      `  ${r.published_month ?? "NULL"},`,
      `  ${sqlArray(r.genres)},`,
      `  ${sqlArray(r.tags)},`,
      `  ${sqlJson(r.external_ids)}::jsonb,`,
      `  ${sqlJson(r.metadata)}::jsonb,`,
      `  ${r.is_verified ? "true" : "false"},`,
      `  ${sqlString(r.source)},`,
      `  ${sqlString(r.source_id)}`,
      `) ON CONFLICT (source, source_id) WHERE source IS NOT NULL AND source_id IS NOT NULL DO UPDATE SET`,
      `  title = EXCLUDED.title,`,
      `  creators = EXCLUDED.creators,`,
      `  cover_url = COALESCE(EXCLUDED.cover_url, items.cover_url),`,
      `  description = COALESCE(EXCLUDED.description, items.description),`,
      `  published_at = COALESCE(EXCLUDED.published_at, items.published_at),`,
      `  published_year = COALESCE(EXCLUDED.published_year, items.published_year),`,
      `  published_month = COALESCE(EXCLUDED.published_month, items.published_month),`,
      `  genres = EXCLUDED.genres,`,
      `  metadata = EXCLUDED.metadata,`,
      `  is_verified = true;`,
      "",
    );
  }

  lines.push("COMMIT;");
  await fs.writeFile(OUT, lines.join("\n"));
  console.log(`Wrote ${rows.length} INSERTs → ${OUT}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
